version: "3.2"
services:

  nats:
    image: nats:latest
    command: -p 4222 --cluster_name "npac-nats-adapter-cluster" -m 8222 -js -V
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      easer-network:
        aliases:
          - nats

networks:
  easer-network:
